// Shared data loader for Faz 6 reporters.
// Tum raporlar ayni veri setini kullansin diye merkezi loader.
import { readFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { listAllObjects, listProjects } from "../markdown/object.mjs";
import { buildBacklinks } from "../markdown/backlinks.mjs";
import { detectHealth } from "../markdown/health.mjs";

export function loadAll(brainRoot) {
  const out = {
    brainRoot,
    canonical: { objects: [], by_project: {}, errors: [] },
    graph: null,
    dry_run: null,
    migrated: null,
    migration_status: "none",   // "none" | "dry-run" | "applied"
    backlinks: null,
    backlinks_broken: [],
    health: null,
    timestamps: {}
  };

  // 1. Canonical objects
  const projects = listProjects(brainRoot);
  for (const project of projects) {
    const objs = listAllObjects(brainRoot, project);
    out.canonical.by_project[project] = objs;
    for (const o of objs) {
      out.canonical.objects.push(o);
      if (o.error) out.canonical.errors.push({ file: o.file_path, error: o.error });
    }
  }

  const validObjs = out.canonical.objects.filter(o => !o.error);
  const { backlinks, broken } = buildBacklinks(validObjs);
  out.backlinks = backlinks;
  out.backlinks_broken = broken;
  out.health = detectHealth(validObjs, backlinks);

  // 2. Graph
  const graphPath = join(brainRoot, "graph", "graph.json");
  if (existsSync(graphPath)) {
    try {
      out.graph = JSON.parse(readFileSync(graphPath, "utf8"));
      out.timestamps.graph = statSync(graphPath).mtime.toISOString();
    } catch (e) {
      out.graph = { error: e.message };
    }
  }

  // 3. Migration state — applied snapshot oncelikli, sonra dry-run
  const migratedPath = join(brainRoot, "archive-index", "migrated-records.json");
  const dryRunPath   = join(brainRoot, "archive-index", "migration-dry-run.json");
  const hasMigrated  = existsSync(migratedPath);
  const hasDryRun    = existsSync(dryRunPath);

  if (hasMigrated) {
    try {
      out.migrated = JSON.parse(readFileSync(migratedPath, "utf8"));
      out.timestamps.migrated = statSync(migratedPath).mtime.toISOString();
      out.migration_status = "applied";
      // dry_run bilincli olarak null birakiliyor: compiler artik preview gostermesin.
      // migration-dry-run.json diskte korunur (referans/audit), ama runtime'da yoksay.
    } catch (e) {
      out.migrated = { error: e.message };
      out.migration_status = "applied"; // hala apply yapilmis sayilir, sadece manifest bozuk
    }
  } else if (hasDryRun) {
    try {
      out.dry_run = JSON.parse(readFileSync(dryRunPath, "utf8"));
      out.timestamps.dry_run = statSync(dryRunPath).mtime.toISOString();
      out.migration_status = "dry-run";
    } catch (e) {
      out.dry_run = { error: e.message };
    }
  }

  return out;
}

export function ts() { return new Date().toISOString(); }

export function header(title, note) {
  return [
    `# ${title}`,
    ``,
    `> Auto-generated by \`serif-brain analyze\` at ${ts()}.`,
    note ? `> ${note}` : null,
    ``
  ].filter(Boolean).join("\n");
}

export function badge(s) {
  return ({ critical: "🔴", high: "🟠", medium: "🟡", low: "⚪",
            open: "🟠", active: "🟢", in_progress: "🔵", blocked: "🔴", queued: "⚪",
            done: "✅", rejected: "✗", archived: "📦" })[s] || "·";
}
