// graph.json + graph.dot + graph-analysis.md serializers.
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

export function writeGraphJson(graph, brainRoot) {
  const dir = join(brainRoot, "graph");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, "graph.json");
  writeFileSync(path, JSON.stringify(graph, null, 2));
  return path;
}

// Compact DOT — sadece file/module/route/component nodes + imports/owns edges.
// Tum graph DOT cok buyuk olabilir, ozetle uretiyoruz.
export function writeGraphDot(graph, brainRoot) {
  const dir = join(brainRoot, "graph");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, "graph.dot");

  const lines = [
    "digraph SerifBrainGraph {",
    "  rankdir=LR;",
    "  node [shape=box, fontname=\"Helvetica\", fontsize=10];",
    "  edge [fontname=\"Helvetica\", fontsize=8];",
    ""
  ];

  // Modul rengi ADDAN TURETILIR. Eskiden sabit bir liste vardi ve o liste paket
  // yazarinin kendi urun modulleriydi (contentx/presentx/studiox...) — yani bu
  // araci kuran herkesin grafi gri cikiyor, yalnizca tek bir projede renkleniyordu.
  // Deterministik: ayni modul her kosuda ayni rengi alir.
  const PALET = ["lightblue", "lightgreen", "khaki", "thistle", "lightcoral",
                 "lightcyan", "lightyellow", "lightpink", "palegreen", "lavender"];
  const renkAl = (ad) => {
    if (!ad || ad === "unknown") return "white";
    let h = 0;
    for (let i = 0; i < ad.length; i++) h = (h * 31 + ad.charCodeAt(i)) >>> 0;
    return PALET[h % PALET.length];
  };
  const moduleColor = new Proxy({}, { get: (_, k) => renkAl(String(k)) });

  // Subgraph per module — readability
  const filesByModule = new Map();
  for (const n of graph.nodes) {
    if (!["file","route","component"].includes(n.type)) continue;
    const m = n.module || "unknown";
    if (!filesByModule.has(m)) filesByModule.set(m, []);
    filesByModule.get(m).push(n);
  }

  let cluster = 0;
  for (const [mod, files] of filesByModule) {
    if (files.length === 0) continue;
    lines.push(`  subgraph cluster_${cluster++} {`);
    lines.push(`    label="${mod}";`);
    lines.push(`    style=filled; fillcolor="${moduleColor[mod] || "white"}";`);
    for (const f of files) {
      const lbl = f.path.replace(/"/g, "\\\"");
      lines.push(`    "${f.id}" [label="${lbl.split("/").slice(-2).join("/")}"];`);
    }
    lines.push("  }");
  }

  // Edges (sadece imports)
  for (const e of graph.edges) {
    if (e.type !== "imports") continue;
    lines.push(`  "${e.source}" -> "${e.target}";`);
  }

  lines.push("}");
  writeFileSync(path, lines.join("\n") + "\n");
  return path;
}

export function writeAnalysisReport(graph, analysis, brainRoot) {
  const dir = join(brainRoot, "reports");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, "graph-analysis.md");

  const lines = [];
  lines.push(`# Graph Analysis Report`);
  lines.push(``);
  lines.push(`> Auto-generated by \`serif-brain graph report\` at ${new Date().toISOString()}.`);
  lines.push(`> Build elapsed: **${graph.stats.build_ms}ms**.`);
  lines.push(``);
  lines.push(`## Stats`);
  lines.push(``);
  for (const [k, v] of Object.entries(graph.stats)) lines.push(`- **${k}:** ${v}`);

  function section(title, items, fmt) {
    lines.push(``);
    lines.push(`## ${title} (${items.length})`);
    lines.push(``);
    if (items.length === 0) { lines.push(`*Yok.*`); return; }
    for (const item of items) lines.push(`- ${fmt(item)}`);
  }

  section("1. Orphan Files", analysis.orphan_files,
    o => `\`${o.path}\` _(module: ${o.module})_`);

  lines.push(``);
  lines.push(`## 2. Circular Dependencies (${analysis.circular_dependencies.length})`);
  lines.push(``);
  if (analysis.circular_dependencies.length === 0) lines.push(`*Yok.*`);
  else for (const cyc of analysis.circular_dependencies.slice(0, 20)) {
    lines.push(`- ${cyc.map(p => `\`${p}\``).join(" → ")}`);
  }

  section("3. God Files (top 20)", analysis.god_files,
    g => `\`${g.path}\` — in: **${g.in}**, out: **${g.out}**, total: **${g.total}**`);

  section("4. High-Risk Modules (≥3 critical/high active bugs)", analysis.high_risk_modules,
    m => `**${m.module}** — ${m.count} critical/high bug:\n  ${m.bugs.map(b => `- [${b.priority}] ${b.title}`).join("\n  ")}`);

  section("5. Modules with Many Open Bugs (≥5)", analysis.modules_with_many_open_bugs,
    m => `**${m.module}** — ${m.count} open bug`);

  section("6. Decisions Without Module", analysis.decisions_without_module,
    d => `\`${d.id}\` — ${d.title}`);

  section("7. Bugs Without Owner", analysis.bugs_without_owner,
    b => `[${b.priority}] **${b.title}** — \`${b.id}\` (${b.status})`);

  section("8. Stale Active Decisions (>30d)", analysis.stale_active_decisions,
    d => `\`${d.id}\` — ${d.title} (${d.days_old}d)`);

  section("9. Unresolved Dependencies", analysis.unresolved_dependencies,
    d => `\`${d.name}\` — bare import, package.json'da yok`);

  section("10. Routes Without Module Owner", analysis.routes_without_owner,
    r => `\`${r.path}\``);

  section("11. Components with Too Many Imports (≥15)", analysis.components_with_too_many_imports,
    c => `\`${c.path}\` — ${c.imports} imports`);

  writeFileSync(path, lines.join("\n") + "\n");
  return path;
}
