// serif-brain init — .serif-brain/ yapisini olustur
import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { detectStoreEngine } from "../store/engine.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const TEMPLATES = resolve(HERE, "../../templates");

const PROJECT_SUBDIRS = ["bugs", "decisions", "notes", "modules", "sessions", "sprints"];
const ROOT_LAYOUT_DIRS = ["graph", "reports", "context", "indexes", "archive-index"];

const DEFAULT_PROJECTS = [
  { id: "serif-platform", active: true,  migrate: true,  description: "Flagship: SerifX 360 Electron desktop suite" },
  { id: "mevzuat-ai",     active: false, migrate: false, description: "Archive-only — pre-multi-project schema" },
  { id: "serifLms",       active: false, migrate: false, description: "Archive-only" },
  { id: "seriftech-packages", active: false, migrate: false, description: "Archive-only — npm packages" }
];

function buildDirLayout(projects) {
  const projectDirs = projects
    .filter(p => p.active)
    .flatMap(p => PROJECT_SUBDIRS.map(sub => `objects/projects/${p.id}/${sub}`));
  return [...projectDirs, ...ROOT_LAYOUT_DIRS];
}

function resolveProjects(args) {
  const customId = args.flags.project_id;
  if (!customId) return DEFAULT_PROJECTS;
  const description =
    typeof args.flags.description === "string"
      ? args.flags.description
      : `Custom project: ${customId}`;
  return [{ id: customId, active: true, migrate: false, description }];
}

const VALID_MODULES = [
  "contentx", "presentx", "animatorx", "studiox", "testx",
  "dashboard", "auth", "billing", "shared", "infra", "unknown"
];

const VALID_STATUS = ["queued", "open", "active", "in_progress", "blocked", "done", "rejected", "archived"];
const VALID_PRIORITY = ["critical", "high", "medium", "low"];
const CONTEXT_EXCLUDED_STATUS = ["done", "rejected", "archived"];

function buildConfig(projectRoot, storeEngine, projects) {
  const hasMigrating = projects.some(p => p.migrate);
  const lines = [
    `# serif-brain config — auto-generated by 'serif-brain init'`,
    `# Edit freely. Re-running init will not overwrite this file.`,
    ``,
    `schema_version: "1.0"`,
    `created_at: "${new Date().toISOString()}"`,
    `project_root: "${projectRoot}"`,
    ``,
    `store:`,
    `  engine: ${storeEngine.engine}     # node:sqlite | jsonl`,
    `  db_path: brain.db`,
    `  jsonl_dir: objects-jsonl`,
    `  node_version: "${storeEngine.node_version}"`,
    ``,
    `projects:`,
    ...projects.flatMap(p => [
      `  - id: ${p.id}`,
      `    active: ${p.active}`,
      `    migrate: ${p.migrate}`,
      `    description: "${p.description}"`
    ]),
    ``,
    `valid_modules:`,
    ...VALID_MODULES.map(m => `  - ${m}`),
    ``,
    `valid_status:`,
    ...VALID_STATUS.map(s => `  - ${s}`),
    ``,
    `valid_priority:`,
    ...VALID_PRIORITY.map(p => `  - ${p}`),
    ``,
    `# Context compiler will exclude records with these statuses from Claude context`,
    `context_excluded_status:`,
    ...CONTEXT_EXCLUDED_STATUS.map(s => `  - ${s}`),
    ``,
    `# Status normalization (legacy -> canonical) — applied during ingest/migration`,
    `status_normalization:`,
    `  completed: done`,
    `  closed: done`,
    `  planned: queued`,
    ``,
    `# Module normalization`,
    `module_normalization:`,
    `  testlms: testx`,
    `  TestLMS: testx`,
    `  TestX: testx`,
    `  PresentX: presentx`,
    `  ContentX: contentx`,
    `  AnimatorX: animatorx`,
    `  StudioX: studiox`,
    ``
  ];
  if (hasMigrating) {
    lines.push(
      `# Sources to read during migration (Faz 5). Read-only references.`,
      `legacy_sources:`,
      `  archive_root: "/Users/muhammedserifdemir/SerifBrainArchive/legacy-2026-04-29-230615"`,
      `  read_from_archive: true     # always read from archive, not live sources`,
      ``
    );
  }
  return lines.join("\n");
}

function writeIfMissing(path, content, label) {
  if (existsSync(path)) {
    console.log(`  - skipped (exists): ${label}`);
    return false;
  }
  writeFileSync(path, content);
  console.log(`  + created: ${label}`);
  return true;
}

function copyTemplateIfMissing(src, dst, label) {
  if (existsSync(dst)) {
    console.log(`  - skipped (exists): ${label}`);
    return false;
  }
  writeFileSync(dst, readFileSync(src));
  console.log(`  + created: ${label}`);
  return true;
}

export async function initCommand({ args }) {
  const projectRoot = resolve(args.flags.project || process.cwd());
  const brainRoot = join(projectRoot, ".serif-brain");
  const projects = resolveProjects(args);
  const customId = args.flags.project_id ?? null;

  console.log(`[serif-brain init]`);
  console.log(`  Project:     ${projectRoot}`);
  console.log(`  Brain root:  ${brainRoot}`);
  if (customId) console.log(`  Project ID:  ${customId} (custom, migrate=false)`);
  console.log(``);

  if (!existsSync(projectRoot)) {
    throw new Error(`Project path does not exist: ${projectRoot}`);
  }

  const storeEngine = await detectStoreEngine();
  console.log(`  Store engine: ${storeEngine.engine} (Node ${storeEngine.node_version})`);
  console.log(``);

  const created = existsSync(brainRoot) ? "EXISTS" : "NEW";
  mkdirSync(brainRoot, { recursive: true });
  console.log(`Brain root [${created}]: ${brainRoot}`);

  const dirLayout = buildDirLayout(projects);
  console.log(``);
  console.log(`Klasor yapisi:`);
  for (const dir of dirLayout) {
    const full = join(brainRoot, dir);
    if (existsSync(full)) {
      console.log(`  - skipped (exists): ${dir}/`);
    } else {
      mkdirSync(full, { recursive: true });
      console.log(`  + created: ${dir}/`);
    }
  }

  console.log(``);
  console.log(`Konfigurasyon ve template'ler:`);
  writeIfMissing(join(brainRoot, "config.yaml"), buildConfig(projectRoot, storeEngine, projects), "config.yaml");
  writeIfMissing(join(brainRoot, ".gitignore"), gitignoreContent(), ".gitignore");
  writeIfMissing(join(brainRoot, "README.md"), readmeContent(), "README.md");

  // Object templates (read-only references for human + tooling)
  for (const tpl of ["bug.md", "decision.md", "note.md", "session.md"]) {
    const src = join(TEMPLATES, "object-templates", tpl);
    const dst = join(brainRoot, "indexes", `_template-${tpl}`);
    if (existsSync(src)) copyTemplateIfMissing(src, dst, `indexes/_template-${tpl}`);
  }

  console.log(``);
  console.log(`✓ init complete`);
  console.log(``);
  console.log(`Sonraki adim:`);
  console.log(`  serif-brain doctor --project ${projectRoot}`);
  return 0;
}

function gitignoreContent() {
  return [
    `# serif-brain — derived/cache files only`,
    `# Canonical data (config.yaml, objects/, archive-index/) IS tracked.`,
    ``,
    `# Derived — regenerable via 'serif-brain analyze'`,
    `graph/`,
    `reports/`,
    `context/`,
    `indexes/`,
    ``,
    `# SQLite engine artifacts`,
    `brain.db`,
    `brain.db-journal`,
    `brain.db-shm`,
    `brain.db-wal`,
    ``,
    `# JSONL fallback artifacts (if engine=jsonl)`,
    `objects-jsonl/`,
    ``
  ].join("\n");
}

function readmeContent() {
  return [
    `# .serif-brain — Serif Brain Core canonical store`,
    ``,
    `Bu klasor proje hafizasinin TEK gercek kaynagidir. Eski Obsidian/Graphify/eski`,
    `\`.claude/brain\` YAML sistemine runtime bagimliligi YOKTUR.`,
    ``,
    `## Yapi`,
    ``,
    `- \`config.yaml\` — sema versiyonu, gecerli modul/status/priority listeleri`,
    `- \`objects/projects/<project>/\` — canonical Markdown object dosyalari`,
    `  - \`bugs/\`, \`decisions/\`, \`notes/\`, \`modules/\`, \`sessions/\`, \`sprints/\``,
    `- \`brain.db\` — SQLite (veya \`objects-jsonl/\` JSONL fallback)`,
    `- \`graph/\` — derived: \`graph.json\`, \`graph.dot\``,
    `- \`reports/\` — derived: health/bugs/decisions/architecture/context-pollution/...`,
    `- \`context/\` — derived: Claude context dosyalari`,
    `- \`indexes/\` — derived: project/module/bug/decision/tag/backlink indexleri`,
    `- \`archive-index/\` — legacy migration manifest ve audit raporu`,
    ``,
    `## Komutlar`,
    ``,
    `\`\`\``,
    `serif-brain doctor              # sistem sagligi`,
    `serif-brain ingest legacy --dry-run`,
    `serif-brain migrate --dry-run`,
    `serif-brain scan code`,
    `serif-brain analyze`,
    `serif-brain context`,
    `\`\`\``,
    ``,
    `## Notlar`,
    ``,
    `- Derived veri (\`graph/\`, \`reports/\`, \`context/\`, \`indexes/\`) silinebilir;`,
    `  \`serif-brain analyze\` ile yeniden uretilir.`,
    `- \`done\`, \`rejected\`, \`archived\` kayitlar Claude aktif context'ine girmez.`,
    `- Eski Obsidian vault sadece migration kaynagidir — runtime'da okunmaz.`,
    ``
  ].join("\n");
}
