// Markdown index generators. Tum ciktilar derived; .gitignore'lu.
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { isContextExcluded, getConfig } from "./schema.mjs";

function ts() { return new Date().toISOString(); }

function header(title, opts = {}) {
  return [
    `# ${title}`,
    ``,
    `> Auto-generated by \`serif-brain rebuild-indexes\` at ${ts()}.`,
    `> **Do not edit manually** — changes will be overwritten.`,
    opts.note ? `>` : null,
    opts.note ? `> ${opts.note}` : null,
    ``
  ].filter(x => x !== null).join("\n");
}

function groupBy(arr, key) {
  const map = new Map();
  for (const item of arr) {
    const k = typeof key === "function" ? key(item) : item[key];
    if (!map.has(k)) map.set(k, []);
    map.get(k).push(item);
  }
  return map;
}

function modulesOf(fm) {
  if (Array.isArray(fm.module)) return fm.module;
  if (fm.module) return [fm.module];
  return ["unknown"];
}

function objectFmList(objects, type) {
  return objects.filter(o => !o.error && o.frontmatter.type === type).map(o => o.frontmatter);
}

function statusBadge(status) {
  const map = {
    open: "🟠",
    active: "🟢",
    in_progress: "🔵",
    blocked: "🔴",
    queued: "⚪",
    done: "✅",
    rejected: "✗",
    archived: "📦"
  };
  return map[status] || "·";
}

function priorityBadge(p) {
  return p ? `[${p}]` : "";
}

// ─── 1. Project index ───
export function buildProjectIndex(objects, indexesDir) {
  const config = getConfig();
  const lines = [header("Project Index", { note: "Aktif proje durumu, modül ve obje sayıları." })];

  const byProject = groupBy(objects.filter(o => !o.error), o => o.frontmatter.project || "unknown");
  for (const project of (config.projects || []).map(p => p.id).concat([...byProject.keys()])) {
    if (!byProject.has(project)) continue;
    if (!lines.find(l => l.startsWith(`## ${project}`))) {
      const objs = byProject.get(project);
      const counts = {
        bug: objs.filter(o => o.frontmatter.type === "bug").length,
        decision: objs.filter(o => o.frontmatter.type === "decision").length,
        note: objs.filter(o => o.frontmatter.type === "note").length,
        session: objs.filter(o => o.frontmatter.type === "session").length
      };
      const active = objs.filter(o => !isContextExcluded(o.frontmatter)).length;
      lines.push(``);
      lines.push(`## ${project}`);
      lines.push(``);
      lines.push(`- **Total:** ${objs.length} objects (${active} active in context)`);
      lines.push(`- **Bugs:** ${counts.bug}`);
      lines.push(`- **Decisions:** ${counts.decision}`);
      lines.push(`- **Notes:** ${counts.note}`);
      lines.push(`- **Sessions:** ${counts.session}`);
    }
  }
  if (byProject.size === 0) {
    lines.push(`*Henüz hiç obje yok. \`serif-brain add bug\` veya \`serif-brain add decision\` ile başlayın.*`);
  }
  writeFileSync(join(indexesDir, "project-index.md"), lines.join("\n") + "\n");
}

// ─── 2. Module index ───
export function buildModuleIndex(objects, indexesDir) {
  const config = getConfig();
  const lines = [header("Module Index", { note: "Modül başına bug/decision/risk durumu." })];

  const moduleStats = new Map();
  for (const m of config.valid_modules) moduleStats.set(m, { bugs: [], decisions: [], notes: [] });

  for (const obj of objects) {
    if (obj.error) continue;
    const fm = obj.frontmatter;
    const mods = modulesOf(fm);
    for (const m of mods) {
      if (!moduleStats.has(m)) moduleStats.set(m, { bugs: [], decisions: [], notes: [] });
      if (fm.type === "bug") moduleStats.get(m).bugs.push(fm);
      else if (fm.type === "decision") moduleStats.get(m).decisions.push(fm);
      else if (fm.type === "note") moduleStats.get(m).notes.push(fm);
    }
  }

  // Sirala: aktif obje sayisi cok olandan baslayarak
  const sorted = [...moduleStats.entries()].sort((a, b) => {
    const ac = a[1].bugs.filter(x => !isContextExcluded(x)).length + a[1].decisions.filter(x => !isContextExcluded(x)).length;
    const bc = b[1].bugs.filter(x => !isContextExcluded(x)).length + b[1].decisions.filter(x => !isContextExcluded(x)).length;
    return bc - ac;
  });

  for (const [mod, stats] of sorted) {
    const totalActive = stats.bugs.filter(x => !isContextExcluded(x)).length + stats.decisions.filter(x => !isContextExcluded(x)).length;
    if (totalActive === 0 && stats.bugs.length === 0 && stats.decisions.length === 0) continue;
    lines.push(``);
    lines.push(`## ${mod}`);
    lines.push(``);
    lines.push(`- Active bugs: **${stats.bugs.filter(x => !isContextExcluded(x)).length}** / ${stats.bugs.length} total`);
    lines.push(`- Active decisions: **${stats.decisions.filter(x => !isContextExcluded(x)).length}** / ${stats.decisions.length} total`);
    lines.push(`- Notes: ${stats.notes.length}`);

    const criticalBugs = stats.bugs.filter(b => b.priority === "critical" && !isContextExcluded(b));
    if (criticalBugs.length > 0) {
      lines.push(``);
      lines.push(`**Critical open bugs (${criticalBugs.length}):**`);
      for (const b of criticalBugs) lines.push(`- [[${b.id}]] ${b.title}`);
    }
  }
  writeFileSync(join(indexesDir, "module-index.md"), lines.join("\n") + "\n");
}

// ─── 3. Bug index ───
export function buildBugIndex(objects, indexesDir) {
  const lines = [header("Bug Index", { note: "Status'a göre gruplanmış. Done/archived hariç tutuldu." })];
  const bugs = objectFmList(objects, "bug");
  const byStatus = groupBy(bugs, "status");

  const statusOrder = ["open", "active", "in_progress", "blocked", "queued", "done", "rejected", "archived"];
  for (const status of statusOrder) {
    const list = byStatus.get(status) || [];
    if (list.length === 0) continue;
    lines.push(``);
    lines.push(`## ${statusBadge(status)} ${status} (${list.length})`);
    lines.push(``);
    list.sort((a, b) => {
      const order = { critical: 0, high: 1, medium: 2, low: 3 };
      return (order[a.priority] ?? 4) - (order[b.priority] ?? 4);
    });
    for (const b of list) {
      const mods = modulesOf(b).join(", ");
      lines.push(`- ${priorityBadge(b.priority)} **${b.title}** — \`${b.id}\` (${mods})`);
    }
  }
  if (bugs.length === 0) lines.push(`*Henüz hiç bug yok.*`);
  writeFileSync(join(indexesDir, "bug-index.md"), lines.join("\n") + "\n");
}

// ─── 4. Decision index ───
export function buildDecisionIndex(objects, indexesDir) {
  const lines = [header("Decision Index", { note: "Karar durumu ve modül dağılımı." })];
  const decisions = objectFmList(objects, "decision");
  const byStatus = groupBy(decisions, "status");

  const statusOrder = ["active", "in_progress", "queued", "blocked", "done", "rejected", "archived"];
  for (const status of statusOrder) {
    const list = byStatus.get(status) || [];
    if (list.length === 0) continue;
    lines.push(``);
    lines.push(`## ${statusBadge(status)} ${status} (${list.length})`);
    lines.push(``);
    list.sort((a, b) => {
      const order = { critical: 0, high: 1, medium: 2, low: 3 };
      return (order[a.priority] ?? 4) - (order[b.priority] ?? 4);
    });
    for (const d of list) {
      const mods = modulesOf(d).join(", ");
      lines.push(`- ${priorityBadge(d.priority)} **${d.title}** — \`${d.id}\` (${mods})`);
    }
  }
  if (decisions.length === 0) lines.push(`*Henüz hiç karar yok.*`);
  writeFileSync(join(indexesDir, "decision-index.md"), lines.join("\n") + "\n");
}

// ─── 5. Tag index ───
export function buildTagIndex(objects, indexesDir) {
  const lines = [header("Tag Index", { note: "Tag bazlı obje listesi." })];
  const tagMap = new Map();
  for (const obj of objects) {
    if (obj.error) continue;
    const fm = obj.frontmatter;
    const tags = Array.isArray(fm.tags) ? fm.tags : [];
    for (const t of tags) {
      if (!tagMap.has(t)) tagMap.set(t, []);
      tagMap.get(t).push(fm);
    }
  }
  const sorted = [...tagMap.entries()].sort((a, b) => b[1].length - a[1].length);
  for (const [tag, items] of sorted) {
    lines.push(``);
    lines.push(`## #${tag} (${items.length})`);
    lines.push(``);
    for (const fm of items) lines.push(`- [[${fm.id}]] ${fm.title} (${fm.type})`);
  }
  if (tagMap.size === 0) lines.push(`*Henüz hiç tag kullanılmadı.*`);
  writeFileSync(join(indexesDir, "tag-index.md"), lines.join("\n") + "\n");
}

// ─── 6. Backlink index ───
export function buildBacklinkIndex(objects, backlinks, broken, indexesDir) {
  const lines = [header("Backlink Index", { note: "Reverse references: 'X -> Y' = X tarafından Y'ye referans var." })];
  const sorted = [...backlinks.entries()].sort((a, b) => b[1].length - a[1].length);
  for (const [target, refs] of sorted) {
    if (refs.length === 0) continue;
    lines.push(``);
    lines.push(`## ${target} (${refs.length} references)`);
    lines.push(``);
    for (const r of refs) lines.push(`- [[${r.source}]] (via ${r.kind})`);
  }
  if (broken.length > 0) {
    lines.push(``);
    lines.push(`## ⚠ Broken references (${broken.length})`);
    lines.push(``);
    for (const b of broken) lines.push(`- \`${b.source}\` → \`${b.target}\` (via ${b.kind})`);
  }
  if (sorted.length === 0 && broken.length === 0) {
    lines.push(`*Henüz hiç backlink yok.*`);
  }
  writeFileSync(join(indexesDir, "backlink-index.md"), lines.join("\n") + "\n");
}

// ─── 7. Health report ───
export function buildHealthReport(health, indexesDir) {
  const lines = [header("Stale / Orphan / Duplicate Report", { note: "30 günden eski aktif kayıtlar, hiç bağlantısı olmayanlar, isim çakışanlar." })];

  lines.push(``);
  lines.push(`## Stale (${health.stale.length})`);
  lines.push(``);
  if (health.stale.length === 0) lines.push(`*Yok.*`);
  else {
    health.stale.sort((a, b) => b.days_old - a.days_old);
    for (const s of health.stale) {
      lines.push(`- \`${s.id}\` (${s.type}, ${s.status}) — son güncelleme **${s.days_old} gün önce**`);
    }
  }

  lines.push(``);
  lines.push(`## Orphan (${health.orphan.length})`);
  lines.push(``);
  if (health.orphan.length === 0) lines.push(`*Yok.*`);
  else for (const o of health.orphan) lines.push(`- \`${o.id}\` (${o.type})`);

  lines.push(``);
  lines.push(`## Duplicates (${health.duplicates.length})`);
  lines.push(``);
  if (health.duplicates.length === 0) lines.push(`*Yok.*`);
  else for (const d of health.duplicates) {
    lines.push(`- ${d.ids.length}x: \`${d.key}\``);
    for (const id of d.ids) lines.push(`  - ${id}`);
  }

  writeFileSync(join(indexesDir, "stale-report.md"), lines.join("\n") + "\n");
}

export function ensureIndexesDir(brainRoot) {
  const dir = join(brainRoot, "indexes");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  return dir;
}
