// migration-audit.md + context-pollution.md + migration-dry-run.json writers.
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

function ts() { return new Date().toISOString(); }

export function writeMigrationAudit(brainRoot, audit) {
  const dir = join(brainRoot, "reports");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, "migration-audit.md");

  const lines = [];
  lines.push(`# Migration Dry-Run Audit`);
  lines.push(``);
  lines.push(`> Auto-generated by \`serif-brain migrate --dry-run\` at ${ts()}.`);
  lines.push(`> **NO files were written** to canonical store. This is a simulation.`);
  lines.push(`> Apply requires explicit user approval and \`--apply\` flag.`);
  lines.push(``);

  lines.push(`## Source Coverage`);
  lines.push(``);
  for (const s of audit.sources) {
    lines.push(`- **${s.kind}** (${s.path})`);
    lines.push(`  - Records found: ${s.count}`);
    if (s.errors > 0) lines.push(`  - Parse errors: ⚠ ${s.errors}`);
    if (s.note) lines.push(`  - Note: ${s.note}`);
  }

  lines.push(``);
  lines.push(`## Classification Summary`);
  lines.push(``);
  lines.push(`| Action | Count | Description |`);
  lines.push(`|---|---:|---|`);
  lines.push(`| **move** | ${audit.classification.move} | Clean, active records → write to canonical store on apply |`);
  lines.push(`| **summarize** | ${audit.classification.summarize} | Valuable but noisy (daily notes, etc.) → condensed in apply |`);
  lines.push(`| **archive** | ${audit.classification.archive} | Closed/duplicate/low-quality → manifest-only, no canonical write |`);
  lines.push(`| TOTAL | ${audit.classification.total} | |`);

  lines.push(``);
  lines.push(`## Normalizations Applied`);
  lines.push(``);
  if (audit.normalizations.length === 0) {
    lines.push(`*Hicbir normalizasyon gerekmedi.*`);
  } else {
    const byField = {};
    for (const n of audit.normalizations) {
      if (!byField[n.field]) byField[n.field] = [];
      byField[n.field].push(n);
    }
    for (const [field, list] of Object.entries(byField)) {
      lines.push(`### ${field} (${list.length} change${list.length===1?"":"s"})`);
      lines.push(``);
      const counts = {};
      for (const n of list) {
        const k = `${n.from} → ${n.to}`;
        counts[k] = (counts[k] || 0) + 1;
      }
      for (const [k, n] of Object.entries(counts).sort((a,b)=>b[1]-a[1])) {
        lines.push(`- \`${k}\` × ${n}`);
      }
      lines.push(``);
    }
  }

  lines.push(`## Duplicate Clusters (${audit.duplicates.length})`);
  lines.push(``);
  if (audit.duplicates.length === 0) {
    lines.push(`*Hiç duplicate küme yok.*`);
  } else {
    for (const d of audit.duplicates.slice(0, 50)) {
      lines.push(`### ${d.cluster_id} (${d.members.length} members)`);
      lines.push(`Key: \`${d.key}\``);
      lines.push(``);
      for (const m of d.members) {
        lines.push(`- ${m.source_kind}: ${m.source_path} — ${m.title || "(no title)"} [${m.status || "?"}]`);
      }
      lines.push(``);
    }
    if (audit.duplicates.length > 50) {
      lines.push(`_... ${audit.duplicates.length - 50} more clusters in JSON dump._`);
    }
  }

  lines.push(``);
  lines.push(`## Warnings (${audit.warnings.length})`);
  lines.push(``);
  if (audit.warnings.length === 0) lines.push(`*Yok.*`);
  else {
    const counts = {};
    for (const w of audit.warnings) {
      counts[w] = (counts[w] || 0) + 1;
    }
    for (const [w, n] of Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0, 30)) {
      lines.push(`- \`${w}\` × ${n}`);
    }
  }

  lines.push(``);
  lines.push(`## Parse Errors (${audit.parse_errors.length})`);
  lines.push(``);
  if (audit.parse_errors.length === 0) lines.push(`*Yok.*`);
  else for (const e of audit.parse_errors) {
    lines.push(`- \`${e.path}\`: ${e.error}`);
  }

  lines.push(``);
  lines.push(`## What Will Be Written On Apply`);
  lines.push(``);
  lines.push(`If you run \`serif-brain migrate --apply\`:`);
  lines.push(``);
  lines.push(`1. **${audit.classification.move}** Markdown object dosyasi yazilacak under \`.serif-brain/objects/projects/serif-platform/\`:`);
  for (const [type, count] of Object.entries(audit.move_breakdown_by_type || {})) {
    lines.push(`   - ${type}s/: ${count} dosya`);
  }
  lines.push(``);
  lines.push(`2. **${audit.classification.summarize}** kayit ozetlenecek (daily notes → tek bir özet, sprints → arşiv özet)`);
  lines.push(``);
  lines.push(`3. **${audit.classification.archive}** kayit \`.serif-brain/archive-index/\` altinda manifest-only kalacak (canonical store'a girmez)`);
  lines.push(``);
  lines.push(`4. \`SerifBrainArchive/legacy-2026-04-29-230615/\` dokunulmaz, sadece okunur.`);
  lines.push(``);
  lines.push(`5. Eski Obsidian vault, eski \`.claude/brain\`, ve \`.claude/settings.json\` **degismez** (Faz 8'e kadar).`);

  if (audit.graphify_summary) {
    lines.push(``);
    lines.push(`## Graphify Reference (NOT MIGRATED)`);
    lines.push(``);
    const g = audit.graphify_summary;
    lines.push(`- Found: ${g.file_path} (${g.bytes} bytes)`);
    if (g.nodes_mentioned !== null) lines.push(`- Old graph: ${g.nodes_mentioned} nodes, ${g.edges_mentioned} edges, ${g.communities_mentioned} communities`);
    lines.push(`- ${g.decision}`);
  }

  writeFileSync(path, lines.join("\n") + "\n");
  return path;
}

export function writeContextPollution(brainRoot, audit) {
  const dir = join(brainRoot, "reports");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, "context-pollution.md");

  const lines = [];
  lines.push(`# Context Pollution Sources`);
  lines.push(``);
  lines.push(`> Eski sistemde **aktif Claude context'ine yanlislikla giren** veya girebilecek kaynaklar.`);
  lines.push(`> Bu kayitlar yeni canonical store'a TASINMAYACAK ya da \`status:archived\` ile gelecek.`);
  lines.push(``);

  const byKind = audit.pollution || {};

  lines.push(`## Closed bugs/decisions (status: done/rejected/archived)`);
  lines.push(``);
  lines.push(`Eski sistemde bu kayitlar generated CLAUDE.md'ye dahil edilmis ve gunluk context'i sismislerdi.`);
  lines.push(``);
  lines.push(`- Closed bugs: **${(byKind.closed_bugs || []).length}**`);
  lines.push(`- Done/archived decisions: **${(byKind.done_decisions || []).length}**`);
  lines.push(``);

  lines.push(`## Triple-duplication (legacy YAML + Obsidian + CLAUDE.md)`);
  lines.push(``);
  lines.push(`- Cluster sayisi: **${audit.duplicates.length}**`);
  lines.push(`- Toplam dupe kayit: **${audit.duplicate_record_count || 0}**`);
  lines.push(``);
  lines.push(`Yeni sistem: tek canonical Markdown object, otomatik backlink. Eski 3'lu kopyalama biter.`);
  lines.push(``);

  lines.push(`## Daily notes (yuksek hacim, dusuk degerli context)`);
  lines.push(``);
  lines.push(`- Daily not sayisi: **${(byKind.daily_notes || []).length}** (4-obsidian-vault/daily/)`);
  lines.push(`- Karar: tek tek tasinmaz; \`summarize\` kategorisinde kalir.`);
  lines.push(``);

  lines.push(`## Closed sprints`);
  lines.push(``);
  lines.push(`- Sprint dosyasi sayisi: **${(byKind.sprint_files || []).length}**`);
  lines.push(`- Aktif sprint(ler): \`move\`, kalan: \`archive\`.`);
  lines.push(``);

  lines.push(`## Deprecated module names`);
  lines.push(``);
  lines.push(`- \`testlms\` → \`testx\` rename: **${audit.module_renames || 0}** kayit etkilendi`);
  lines.push(``);

  lines.push(`## TOP priority anomalies`);
  lines.push(``);
  lines.push(`- TOP olarak gelen priority sayisi: **${audit.top_priority_count || 0}**`);
  lines.push(`- Default tedavi: \`high\`. Manual review onerisi raporlandi.`);
  lines.push(``);

  lines.push(`## Graphify cache (10 MB)`);
  lines.push(``);
  lines.push(`Eski sistemde \`PreToolUse\` hook'u Glob/Grep oncesi GRAPH_REPORT.md okutuyordu.`);
  lines.push(`Yeni sistemde Faz 4 native graph engine var, eski cache dis bagimliligi gerektirmez.`);
  lines.push(`Faz 8'de bu hook devreden cikarilacak.`);

  writeFileSync(path, lines.join("\n") + "\n");
  return path;
}

export function writeDryRunJson(brainRoot, audit) {
  const dir = join(brainRoot, "archive-index");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, "migration-dry-run.json");
  writeFileSync(path, JSON.stringify(audit, null, 2));
  return path;
}
